endpoint: http://zabbix-graphql-api:4000/graphql
overrides:
  mutation_mode: all
transport:
  type: streamable_http
  address: 0.0.0.0
  port: 3000
  stateful_mode: false
operations:
  source: local
  paths:
    - /mcp/operations
schema:
  source: local
  path: /mcp-data/schema.graphql
introspection:
  execute:
    enabled: true
  introspect:
    enabled: true
  search:
    enabled: true
logging:
  level: ${env.MCP_LOG_LEVEL:-info}
